name: Node.js CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Using npm ci installs the versions in the package-lock.json or
      # npm-shrinkwrap.json file and prevents updates to the lock file.
      # Using npm ci is generally faster than running npm install.
      # For more information, see npm ci and "Introducing npm ci for
      # faster, more reliable builds".
      # Alternatively, you can pass --frozen-lockfile to install the
      # versions in the yarn.lock file and prevent updates to the
      # yarn.lock file.
      - run: yarn --frozen-lockfile
      - run: npm run build --if-present
      - run: npm test
